transformlivedata:
  warning_window:
    type: "time"
    value: 24
  warning_thresholds:
    max_failed_items: 500
    max_failed_ratio: 0.02
    max_consecutive_warn: 3
  notify_on_fail: true
  notify_on_warn: true
gtfs:
  warning_window:
    type: "time"
    value: 24
  warning_thresholds:
    max_failed_items: 1
    max_failed_ratio: 1
    max_consecutive_warn: 3
  notify_on_fail: true
  notify_on_warn: true
extractloadlivedata:
  warning_window:
    type: "time"
    value: 24
  warning_thresholds:
    max_failed_items: 1
    max_failed_ratio: 1
    max_consecutive_warn: 3
  notify_on_fail: true
  notify_on_warn: true
