"""Application-level logging taxonomy for transformlivedata."""

from typing import Literal, TypeAlias

EventType: TypeAlias = Literal[
    "config_load_failed",
    "execution_finished",
    "execution_started",
    "expectations_validation_failed",
    "expectations_validation_started",
    "ingest_requests_fetch_empty",
    "ingest_requests_fetch_started",
    "ingest_requests_fetch_succeeded",
    "logical_date_context_build_failed",
    "phase_started",
    "positions_decompression_started",
    "positions_distance_calculation_empty",
    "positions_empty",
    "positions_enrichment_all_invalid",
    "positions_enrichment_empty",
    "positions_flattening_empty",
    "positions_json_parse_failed",
    "positions_load_failed",
    "positions_metadata_missing_extracted_at",
    "positions_normalization_empty",
    "positions_payload_loaded",
    "positions_read_failed",
    "positions_read_started",
    "positions_save_failed",
    "positions_save_skipped_empty",
    "positions_save_started",
    "positions_save_succeeded",
    "positions_transform_empty",
    "positions_transform_failed",
    "positions_transform_started",
    "positions_transform_summary",
    "quality_report_expectations_parse_failed",
    "quality_report_failure_write_failed",
    "quality_report_formatted_summary",
    "quality_report_parse_failed",
    "quarantine_positions_save_failed",
    "quarantine_positions_save_started",
    "quarantine_positions_saved",
    "raw_schema_validation_failed",
    "raw_schema_validation_succeeded",
    "request_mark_by_filename_failed",
    "request_mark_by_filename_started",
    "request_mark_by_filename_succeeded",
    "request_mark_processed_failed",
    "request_mark_processed_started",
    "request_mark_processed_succeeded",
    "trip_details_cache_built",
    "trip_details_load_failed",
    "trip_details_load_started",
    "trip_details_load_succeeded",
    "trip_details_preload_empty",
    "trip_details_preload_started",
    "trusted_positions_save_failed",
    "trusted_positions_save_started",
    "trusted_positions_saved",
]

