"""Application-level logging taxonomy for transformlivedata."""

from typing import Literal, TypeAlias, Union

_OrchestratorEvent: TypeAlias = Literal[
    "config_load_started",
    "config_load_succeeded",
    "execution_failed",
    "execution_finished",
    "execution_phase_metrics",
    "execution_started",
    "expectations_validation_started",
    "expectations_validation_succeeded",
    "failure_report_error",
    "failure_report_skipped",
    "load_positions_failed",
    "load_positions_started",
    "load_positions_succeeded",
    "mark_processed_started",
    "mark_processed_succeeded",
    "quality_report_metrics",
    "quality_report_started",
    "quality_report_succeeded",
    "raw_schema_validation_failed",
    "raw_schema_validation_started",
    "raw_schema_validation_succeeded",
    "save_positions_skipped",
    "save_positions_started",
    "save_positions_succeeded",
    "transform_failed",
    "transform_started",
    "transform_succeeded",
]

_ServiceEvent: TypeAlias = Literal[
    "build_logical_date_context_failed",
    "distance_calculation_failed",
    "get_unprocessed_requests_failed",
    "get_unprocessed_requests_started",
    "get_unprocessed_requests_succeeded",
    "load_positions_decompression_failed",
    "load_positions_decompression_started",
    "load_positions_decompression_succeeded",
    "load_positions_json_parse_failed",
    "load_positions_json_parse_succeeded",
    "load_positions_storage_read_failed",
    "load_positions_storage_read_started",
    "load_positions_storage_read_succeeded",
    "load_trip_details_failed",
    "load_trip_details_started",
    "load_trip_details_succeeded",
    "mark_request_as_processed_failed",
    "mark_request_by_filename_failed",
    "mark_request_by_filename_started",
    "mark_request_by_filename_succeeded",
    "quality_report_build_failed",
    "save_positions_export_started",
    "save_positions_failed",
    "save_positions_invalid_target_bucket",
    "save_positions_skipped_empty",
    "transform_positions_failed",
    "transform_positions_invalid_trips_detected",
    "transform_positions_invalid_vehicle_ids_detected",
    "transform_positions_metrics",
]

EventType: TypeAlias = Union[_OrchestratorEvent, _ServiceEvent]
